
import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'placehold.co' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: 'picsum.photos' },
      { protocol: 'https', hostname: '**.glbimg.com' },
      { protocol: 'https', hostname: 'minhasreceitinhas.com.br' },
      { protocol: 'https', hostname: '**.sadia.com.br' },
      { protocol: 'https', hostname: '**.tudoreceitas.com' },
      { protocol: 'https', hostname: 'melevacontigo.com.br' },
      { protocol: 'https', hostname: 'sabores-new.s3.amazonaws.com' },
      { protocol: 'https', hostname: '**.itdg.com.br' },
      { protocol: 'https', hostname: '**.umcomo.com.br' },
      { protocol: 'https', hostname: 'encrypted-tbn0.gstatic.com' },
      { protocol: 'https', hostname: 'chaparadois.com.br' },
      { protocol: 'https', hostname: '**.vilma.com.br' },
      { protocol: 'https', hostname: 'naturaves.com.br' },
      { protocol: 'https', hostname: 'sabordasespeciarias.com.br' },
      { protocol: 'https', hostname: '**.oitedi.com.br' },
      { protocol: 'https', hostname: 'conteudo.imguol.com.br' },
      { protocol: 'https', hostname: 'boomi.b-cdn.net' },
      { protocol: 'https', hostname: '**.comidaereceitas.com.br' },
      { protocol: 'https', hostname: '**.academiaassai.com.br' },
      { protocol: 'https', hostname: 'receitasobremesa.com.br' },
      { protocol: 'https', hostname: 'i0.wp.com' },
      { protocol: 'https', hostname: '**.wine.com.br' },
      { protocol: 'https', hostname: '**.dicasdetreino.com.br' },
      { protocol: 'https', hostname: '**.receitadevovo.com.br' },
      { protocol: 'https', hostname: 'd2qcpt1idvpipw.cloudfront.net' },
      { protocol: 'https', hostname: 'anamariareceitas.com.br' },
      { protocol: 'https', hostname: '**.panelinha.com.br' },
      { protocol: 'https', hostname: 'benditosalgado.com.br' },
      { protocol: 'https', hostname: '**.cordonbleu.edu' },
      { protocol: 'https', hostname: '**.freepik.com' },
      { protocol: 'https', hostname: 'cozinhafitsemsegredos.com' },
      { protocol: 'https', hostname: '**.entrepratosecopos.com.br' },
      { protocol: 'https', hostname: 'assets.unileversolutions.com' },
      { protocol: 'https', hostname: 'bolinhodecoco.pt' },
      { protocol: 'https', hostname: '**.receitasnestle.com.br' },
      { protocol: 'https', hostname: '**.seara.com.br' },
      { protocol: 'https', hostname: '**.rampinelli.com.br' },
      { protocol: 'https', hostname: 'amopaocaseiro.com.br' },
      { protocol: 'https', hostname: 'lirp.cdn-website.com' },
      { protocol: 'https', hostname: 'pt.petitchef.com' },
      { protocol: 'https', hostname: '**.doceiguaria.com.br' },
      { protocol: 'https', hostname: '**.manusmenu.com' },
      { protocol: 'https', hostname: 'delicious.com.br' },
      { protocol: 'https', hostname: 'docepedia.com' },
      { protocol: 'https', hostname: 'smartfarmer.pt' },
      { protocol: 'https', hostname: 'p2.trrsf.com' },
      { protocol: 'https', hostname: 'redacaors.com.br' },
      { protocol: 'https', hostname: '**.mendezalimentos.com.br' },
      { protocol: 'https', hostname: 'www.nattyspantry.com' },
    ],
  },
};

export default nextConfig;
